zk-org/zk

CHANGELOG.md, adapter/markdown/extensions/tag.go, adapter/markdown/extensions/wikilink.go, adapter/markdown/markdown.go, adapter/markdown/markdown_test.go, adapter/sqlite/collection_dao.go, adapter/sqlite/collection_dao_test.go, adapter/sqlite/db.go, adapter/sqlite/db_test.go, adapter/sqlite/fixtures/default/collections.yml, adapter/sqlite/fixtures/default/notes_collections.yml, adapter/sqlite/note_dao.go, adapter/sqlite/note_dao_test.go, adapter/sqlite/note_indexer.go, adapter/sqlite/note_indexer_test.go, adapter/sqlite/transaction_test.go, cmd/container.go, cmd/index.go, core/ids.go, core/note/index.go, core/note/parse.go, docs/.zk/templates/default.md, util/strings/strings.go, util/test/assert/assert.go
Fix #2
Many tag flavors are supported: `#hashtags`, `:colon:separated:tags:` and even Bear's [`#multi-word tags#`](https://blog.bear.app/2017/11/bear-tips-how-to-create-multi-word-tags/). If you prefer to use a YAML frontmatter, list your tags with the keys `tags` or `keywords`.
I created a generic `collections` table with a `kind` column (e.g. `tag`) to hold the tags. In the future, this could be extended for other kinds of metadata (categories, author, etc.).
=> Parse tags in Markdown documents

CHANGELOG.md, cmd/container.go, cmd/edit.go, cmd/index.go, cmd/list.go, cmd/new.go, core/note/create.go, core/zk/config.go, core/zk/config_test.go, core/zk/zk.go, docs/config.md, main.go, util/test/assert/assert.go
Fix #10 
* Global `zk` configuration at `~/.config/zk/config.toml`.
* Useful to share aliases or default settings across several notebooks.
* This is the same format as a notebook configuration file.
* Shared templates can be stored in `~/.config/zk/templates/`.
* `XDG_CONFIG_HOME` is taken into account.
=> Add a global configuration file

CHANGELOG.md, cmd/container.go, cmd/edit.go, cmd/index.go, cmd/list.go, cmd/new.go, core/zk/zk.go, docs/config-alias.md, docs/daily-journal.md, docs/notebook.md, main.go
Fix #13
* Use `--notebook-dir` or set `ZK_NOTEBOOK_DIR` to run `zk` as if it was started from this path instead of the current working directory.
* This allows running `zk` without being in a notebook.
* By setting `ZK_NOTEBOOK_DIR` in your shell configuration file (e.g. `~/.profile`), you are declaring a default global notebook which will be used when `zk` is not in a notebook.
* When the notebook directory is set explicitly, any path given as argument will be relative to it instead of the actual working directory.
=> Specify the notebook directory explicitly

CHANGELOG.md, adapter/sqlite/db.go, adapter/sqlite/note_dao.go, adapter/sqlite/note_dao_test.go, cmd/finder_opts.go, core/note/find.go, docs/config-alias.md, docs/note-filtering.md
* Find every note whose title is mentioned in the note you are working on with `--mentioned-by file.md`.
* To refer to a note using several names, you can use the [YAML frontmatter key `aliases`](https://publish.obsidian.md/help/How+to/Add+aliases+to+note). For example the note titled "Artificial Intelligence" might have: `aliases: [AI, robot]`
* To find only unlinked mentions, pair it with `--no-linked-by`, e.g. `--mentioned-by file.md --no-linked-by file.md`.
=> Add the --mentioned-by filtering option

CHANGELOG.md, README.md, cmd/edit.go, cmd/finder_opts.go, cmd/finder_opts_test.go, cmd/list.go, core/zk/config.go, core/zk/config_test.go, core/zk/zk.go, docs/automation.md, docs/config-alias.md, docs/config-filter.md, docs/config.md, docs/note-filtering.md, util/strings/strings.go, util/strings/strings_test.go
* Declare [named filters](docs/config-filter.md) in the configuration file to reuse [note filtering options](docs/note-filtering.md) used frequently together, for example:
```toml
[filter]
recents = "--sort created- --created-after 'last two weeks'"
```
```sh
$ zk list recents --limit 10
$ zk edit recents --interactive
```
=> Add named filters

CHANGELOG.md, internal/adapter/fs/fs.go, internal/adapter/fzf/note_filter.go, internal/cli/cmd/edit.go, internal/cli/cmd/list.go, internal/cli/container.go, internal/core/fs.go, internal/core/fs_test.go, internal/core/note_new_test.go, internal/core/notebook.go, main.go
* `--notebook-dir` does not change the working directory anymore, instead it sets manually the current notebook and disable auto-discovery. Use the new `--working-dir`/`-W` flag to run `zk` as if it was started from this path instead of the current working directory.
* For convenience, `ZK_NOTEBOOK_DIR` behaves like setting a `--working-dir` fallback, instead of `--notebook-dir`. This way, paths will be relative to the root of the notebook.
* A practical use case is to use `zk list -W .` when outside a notebook. This will list the notes in `ZK_NOTEBOOK_DIR` but print paths relative to the current directory, making them actionable from your terminal emulator.
This initial work will be useful to generate relative Markdown links by changing the reference point without manual `cd`.
=> Add --working-dir option

CHANGELOG.md, docs/note-filtering.md, internal/adapter/sqlite/note_dao.go, internal/adapter/sqlite/note_dao_test.go, internal/adapter/sqlite/testdata/default/notes.yml, internal/adapter/sqlite/util.go, internal/adapter/sqlite/util_test.go, internal/cli/filtering.go, internal/cli/filtering_test.go, internal/core/note_find.go
* Pair `--match` with `--exact-match` / `-e` to search for (case insensitive) exact occurrences in your notes.
* This can be useful when looking for terms including special characters, such as `[[name]]`.
=> Add --exact-match option

CHANGELOG.md, docs/tool-fzf.md, internal/adapter/fzf/note_filter.go, internal/cli/cmd/edit.go, internal/cli/cmd/list.go, internal/cli/container.go, internal/core/config.go, internal/core/config_test.go, internal/core/notebook_store.go
* Customize the format of `fzf`'s lines [with your own template](docs/tool-fzf.md).
```toml
[tool]
fzf-line = "{{style 'green' path}}{{#each tags}} #{{this}}{{/each}} {{style 'black' body}}"
```
* Creating a new note from `fzf` in a directory containing spaces (cc @sharpevo thanks for spotting that!)
=> Customize the format of fzf's lines with your own template

internal/adapter/lsp/server.go, internal/adapter/lsp/util.go
For paths like `/path to my/zettelkasten`. Uses the `url` package from Go.
=> lsp: parse URIs properly to allow spaces in paths

CHANGELOG.md, docs/config-lsp.md, docs/config.md, docs/editors-integration.md, internal/adapter/lsp/document.go, internal/adapter/lsp/server.go, internal/cli/container.go, internal/core/config.go, internal/core/config_test.go, internal/core/notebook_store.go, main.go
* LSP diagnostics to [report dead links or wiki-link titles](docs/config-lsp.md).
(Diagnostics are displayed as virtual text with Neovim 0.5's built-in LSP client)
=> Publish LSP diagnostics for dead links and wiki-link titles

CHANGELOG.md, internal/adapter/lsp/server.go, internal/core/link_format.go, internal/core/link_format_test.go
* Auto-complete only the path of a Markdown link by typing `[custom title]((`.
=> Auto-complete only the path of a Markdown link

README.md
Now that the `go` script no longer exists in the repo, the chmod command isn't needed.
BTW zk is a great tool, I'm absolutely loving it. Thanks!
=> remove go chmod command from README.md

CHANGELOG.md, internal/adapter/lsp/server.go
The LSP returns a list of references to the link that is pointed to.
=> lsp: add references support for links

CHANGELOG.md, docs/config-note.md, internal/core/config.go, internal/core/config_test.go, internal/core/note_index.go, internal/core/notebook_store.go, internal/util/paths/walk.go, internal/util/paths/walk_test.go
See discussion https://github.com/mickael-menu/zk/discussions/56
* New [`note.ignore`](docs/config-note.md) configuration option to ignore files matching the given path globs when indexing notes.
```yaml
[note]
ignore = [
"log-*.md"
"drafts/*"
]
```
=> Add a new configuration option to ignore files when indexing notes

docs/template-format.md, internal/core/note_format.go, internal/core/note_format_test.go
Adds a full path for the note to the list template to make integration easier.
=> Add "abs-path" to template-format

CHANGELOG.md, main.go
Fix #66 
* Allow setting the `--working-dir` and `--notebook-dir` flags before the `zk` subcommand when using aliases, e.g. `zk -W ~/notes my-alias`.
=> Allow setting the --working-dir and --notebook-dir flags before the subcommand when using aliases

internal/adapter/lsp/document.go
Enable compatibility with [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax)
=> Support pandoc filetype

CHANGELOG.md, internal/adapter/lsp/server.go
* Support for LSP references to browse the backlinks of the current note, if the caret is not over a link.
=> LSP references for the current note

CHANGELOG.md, internal/core/note_index.go
* [#78](https://github.com/mickael-menu/zk/issues/78) Do not exclude notes containing broken links from the index.
=> Do not exclude notes containing broken links from the index

CHANGELOG.md, internal/cli/cmd/new.go, internal/core/note_new.go, internal/core/note_parse.go, internal/core/notebook.go
Fix #93 
* New `--dry-run` flag for `zk new` which prints out the path and content of the generated note instead of saving it to the file system.
=> Add `--dry-run` flag for `zk new`

CHANGELOG.md, internal/adapter/lsp/server.go, internal/cli/cmd/index.go, internal/cli/cmd/init.go, internal/core/note_index.go, internal/core/notebook.go, internal/util/paths/diff.go, internal/util/paths/diff_test.go, main.go
* New `--verbose` flag for `zk index` which prints detailed information about the indexing process.
=> Add a verbose mode to `zk index`

CHANGELOG.md, internal/adapter/lsp/document.go, internal/adapter/lsp/server.go, internal/adapter/markdown/markdown.go, internal/adapter/markdown/markdown_test.go, internal/adapter/sqlite/db.go, internal/adapter/sqlite/db_test.go, internal/adapter/sqlite/note_dao.go, internal/adapter/sqlite/note_dao_test.go, internal/adapter/sqlite/testdata/sample.db, internal/core/link.go, internal/core/note_find.go, internal/core/notebook.go
Fix #98 
* [#98](https://github.com/mickael-menu/zk/issues/98) Index wiki links using partial paths for `--linked-by` and `--link-to`.
* [#98](https://github.com/mickael-menu/zk/issues/98) Ignore spaces around the pipe in wiki links for LSP diagnostics.
=> Fix indexing wiki links using partial paths

CHANGELOG.md, docs/tool-fzf.md, internal/adapter/fzf/note_filter.go, internal/adapter/handlebars/handlebars_test.go
* You can now filter through the [YAML frontmatter](docs/note-frontmatter.md) with `zk list --interactive`.
---
* Fix #109
=> Filter through the note frontmatter with `--interactive`

CHANGELOG.md, internal/adapter/lsp/server.go, internal/adapter/sqlite/note_dao.go, internal/adapter/sqlite/note_dao_test.go, internal/adapter/sqlite/testdata/default/notes.yml, internal/cli/filtering.go, internal/core/note_find.go, internal/core/notebook.go
* [#111](https://github.com/mickael-menu/zk/issues/111) Filenames take precedence over folders when matching a sub-path with wiki links.
---
* Fix #111
=> Make filename take precedence over folders when matching sub-paths

CHANGELOG.md, docs/editors-integration.md, internal/adapter/lsp/cmd_index.go, internal/adapter/lsp/cmd_list.go, internal/adapter/lsp/cmd_new.go, internal/adapter/lsp/cmd_tag.go, internal/adapter/lsp/server.go, internal/adapter/sqlite/collection_dao.go, internal/adapter/sqlite/collection_dao_test.go, internal/cli/filtering.go, internal/core/collection.go, internal/util/strings/strings.go
* New LSP commands:
* [`zk.list`](docs/editors-integration.md#zklist) to search for notes.
* [`zk.tag.list`](docs/editors-integration.md#zktaglist) to retrieve the list of tags.
---
Here's an example with Neovim:
```viml
:ZkList { select = {'filename', 'title'}, linkTo = {'a-note.md'} }
:ZkTagList { sort = {'note-count'} }
```
With the config:
```viml
command! -nargs=? ZkList :lua zkList(<args>)
command! -nargs=? ZkTagList :lua zkTagList(<args>)
lua << EOF
function zkList(...)
vim.lsp.buf_request(0, 'workspace/executeCommand',
{
command = 'zk.list',
arguments = {
vim.api.nvim_buf_get_name(0),
...
},
},
function(_, result, _, _)
print(vim.inspect(result))
end
)
end
function zkTagList(...)
vim.lsp.buf_request(0, 'workspace/executeCommand',
{
command = 'zk.tag.list',
arguments = { …
```
=> Add LSP commands `zk.list` and `zk.tag.list`

internal/adapter/sqlite/note_dao.go, internal/adapter/sqlite/note_dao_test.go
If `--link-to` didn't match any note, then it's as if there was no filter anymore. Now an error is returned instead.
=> Don't match all notes when `--link-to` or `--linked-by` have no match

CHANGELOG.md, internal/adapter/markdown/extensions/tag.go, internal/adapter/markdown/markdown_test.go, main.go
* `--debug` mode which prints a stacktrace on `SIGINT`.
* [#118](https://github.com/mickael-menu/zk/issues/118) Fix infinite loop when parsing a single-character hashtag.
---
* Fix #118
=> Fix infinite loop when parsing a single-character hashtag

CHANGELOG.md, internal/cli/cmd/init.go, internal/core/notebook_store.go
* [#121](https://github.com/mickael-menu/zk/issues/121) Take into account the `--no-input` flag with `zk init`.
---
* Fix #121
=> Take into account `--no-input` with `zk init`

CHANGELOG.md, internal/util/date/date.go
* [#120](https://github.com/mickael-menu/zk/discussions/120) Support RFC 3339 dates with the time flags (e.g. `--created-before`).
=> Support RFC 3339 dates with the time flags

CHANGELOG.md, internal/adapter/lsp/document.go
* [#126](https://github.com/mickael-menu/zk/issues/126) Embedded image links shown as not found.
---
* Fix #126
=> Fix embedded image links shown as not found

README.md
zk has been added to homebrew-core, so we no longer need the custom tap.
https://github.com/Homebrew/homebrew-core/pull/91670
=> Point Homebrew install instructions to homebrew-core

CHANGELOG.md, docs/config-lsp.md, internal/adapter/lsp/server.go, internal/core/config.go, internal/core/config_test.go, internal/util/opt/opt.go
* [zk-nvim#26](https://github.com/mickael-menu/zk-nvim/issues/26) The LSP server doesn't use `additionalTextEdits` anymore to remove the trigger characters when completing links.
* You can customize the default behavior with the [`use-additional-text-edits` configuration key](docs/config-lsp.md).
=> Disable `additionalTextEdits` for completion items by default

CHANGELOG.md, internal/util/exec/exec_unix.go
* [#163](https://github.com/mickael-menu/zk/issues/163) Use the `ZK_SHELL` environment variable to override the shell for `zk` only.
---
* Fix #163
=> Add support for `ZK_SHELL`

CHANGELOG.md, internal/cli/cmd/new.go, internal/core/notebook.go, tests/cmd-new.tesh, tests/fixtures/new/.zk/config.toml
This allows overriding the id generation step and just use a provided
value instead.
=> Add `--id` flag to `zk new`

CHANGELOG.md, go.mod, go.sum, internal/core/note_index.go, tests/issue-173.tesh
* [#173](https://github.com/mickael-menu/zk/issues/173) Support for double star globbing in `note.ignore` config option.
---
* Fix #173
=> Add support for double star globbing in `note.ignore` config option

CHANGELOG.md, internal/adapter/markdown/extensions/tag.go, tests/issue-185.tesh
* [#185](https://github.com/mickael-menu/zk/issues/185) Don't parse a Markdown table header as a colon tag.
---
* Fix #185
=> Don't parse Markdown table headers as colon tags

README.md
Apparently `zk` got added to nixpkgs:
- https://github.com/NixOS/nixpkgs/pull/143020
And incidentally, the vim extension as well (not yet merged):
- https://github.com/NixOS/nixpkgs/pull/164343
=> Add Nix install instructions

.github/workflows/codeql.yml
Enable GitHub code scanning (CodeQL) to find potential errors in the
source code. The configuration file has been generated based on the
example workflow by GitHub.
Code scanning will run periodically and for every pull request.
Alerts will be presented in the Security tab of the project, under Code
scanning alerts. By default, only maintainers of the project can see
these findings.
=> Enable GitHub code scanning

CHANGELOG.md, internal/adapter/lsp/server.go
* The LSP server does not support resolving a wiki link to a note title anymore.
* For example, `[[Planet]]` can match a note with filename `i4w0 Planet.md` but not `i4w0.md` with a Markdown title `Planet` anymore.
* This "smart" fallback resolution based on note titles was too fragile and not supported by the `zk` CLI.
=> LSP: Deprecate title matching for wiki links

CHANGELOG.md, internal/cli/cmd/index.go, internal/cli/cmd/init.go, internal/core/notebook.go, main.go
* [#233](https://github.com/mickael-menu/zk/issues/233) Hide index progress in non-interactive shells.
---
* Fixes #233
=> Hide index progress in non-interactive shells

CHANGELOG.md, internal/cli/cmd/new.go, internal/util/os/os.go, tests/cmd-new.tesh
* [#239](https://github.com/mickael-menu/zk/discussions/239) Support standard input via shell redirection with `zk new`.
=> Support standard input via shell redirection with `zk new`

CHANGELOG.md, internal/adapter/lsp/document.go, internal/util/strings/strings.go, internal/util/strings/strings_test.go
* [#235](https://github.com/mickael-menu/zk/issues/235) Fix LSP link recognition with unicode (contributed by [@zkbpkp](https://github.com/mickael-menu/zk/issues/235)).
---
* Fixes #235
=> Fix LSP link recognition with unicode

CHANGELOG.md, internal/adapter/sqlite/note_index.go, tests/fixtures/issue-236/2022-07-06.md, tests/fixtures/issue-236/8r8q.md, tests/fixtures/issue-236/ud1o.md, tests/issue-236.tesh
* [#236](https://github.com/mickael-menu/zk/issues/236) Fix updating links after creating a new note.
---
* Fixes #236
=> Fix updating links after creating a new note

CHANGELOG.md, internal/adapter/lsp/document.go, internal/adapter/lsp/server.go
* [#243](https://github.com/mickael-menu/zk/issues/243) LSP: Fixed finding backlink references for notes in a folder.
---
* Fix #243
=> LSP: Fix finding backlink references for notes in a folder

docs/editors-integration.md
https://github.com/megalithic/zk.nvim has been archived for a while.
I'm assuming it is intended to link to the same plugin as in `README.md`.
=> Link to mickael-menu/zk-nvim instead of megalithic/zk.nvim

CHANGELOG.md, internal/adapter/lsp/server.go
* LSP: Support for external URLs with `documentLink`.
=> LSP: Add support for external URLs with `documentLink`

main.go, tests/flag-notebook-dir.tesh, tests/flag-working-dir.tesh
--working-dir and --notebook-dir options run through some custom parsing code before everything else so it can apply to aliases.
When given in the form --working-dir=x (with an =), the previous implementation would check this as a single option instead of separating it into an option=value pair, which would mean --working-dir=, -W= and --notebook-dir= would not be recognised when given.
=> Fix --working-dir= and --notebook-dir= option parsing

CHANGELOG.md, docs/editors-integration.md, docs/note-filtering.md, internal/adapter/handlebars/handlebars_test.go, internal/adapter/sqlite/note_dao.go, internal/adapter/sqlite/note_dao_test.go, internal/cli/filtering.go, internal/cli/filtering_test.go, internal/core/note_find.go, internal/core/notebook.go, internal/util/test/assert/assert.go, tests/cmd-graph.tesh, tests/cmd-list-filter-match-exact.tesh, tests/cmd-list-filter-match-fts.tesh, tests/cmd-list-filter-match-re.tesh, tests/cmd-list.tesh
=> Mmmmulti match

CHANGELOG.md, docs/editors-integration.md, internal/adapter/lsp/cmd_new.go
* LSP: `zk.new` now returns the created note's content in its output (`content`), and has two new options:
* `dryRun` will prevent `zk.new` from creating the note on the file system.
* `insertContentAtLocation` can be used to insert the created note's content into an arbitrary location.
---
This can be used to insert a rendered note template into a note, without creating a new file for the note.
=> Add new options for LSP command `zk.new`

CHANGELOG.md, docs/editors-integration.md, internal/adapter/lsp/cmd_link.go, internal/adapter/lsp/cmd_new.go, internal/adapter/lsp/server.go, internal/adapter/lsp/util.go
Allows users to take advantage of the linking mechanism in their editing tools outside of the 'zk.new' context. For example, I made a "ZkInsertLink" command with Neovim that inserts a link at the current cursor location after searching for the desired note. This improves on the current behavior which only autocompletes based on note name, which users may or may not remember.
I looked for a `CONTRIBUTING.md` but couldn't find. I hope you find this PR useful!
- Adds 'zk.link' LSP command
- Refactors linking mechanism from `executeCommandNew` into utility function to be used by both `executeCommandNew` and `executeCommandLink`
=> feat(lsp): add 'zk.link' LSP command

internal/adapter/lsp/server.go
This fixes issue with some clients (see for example this [kak-lsp issue](https://github.com/kak-lsp/kak-lsp/issues/669)) expecting to find a non empty string there to display.
=> Adds "title" to the Command in code actions

CHANGELOG.md, docs/config-notebook.md, docs/config.md, docs/notebook.md, internal/cli/container.go, internal/core/config.go, internal/core/config_test.go, internal/core/notebook_store.go
As mentioned on https://github.com/mickael-menu/zk/issues/300.
This is the proposed solution to add the default notebook path on the `config.toml`.
=> Add `notebook` configuration to set default notebook path

internal/adapter/lsp/document.go, internal/adapter/lsp/server.go
Fix https://github.com/mickael-menu/zk-nvim/issues/69.
According to https://pkg.go.dev/go.lsp.dev/protocol#Position, "The offsets are based on a UTF-16 string representation".
Other code that uses protocol.Position may also have similar issues, but I only fixed the part that affects autocompletion.
=> Use UTF-16 to get the correct position

CHANGELOG.md, docs/config-note.md, internal/core/config.go, internal/core/config_test.go, internal/core/note_index.go, tests/cmd-index-legacy-ignore.tesh, tests/cmd-index.tesh, tests/config-note-exclude.tesh, tests/fixtures/legacy-ignore/.zk/config.toml, tests/fixtures/legacy-ignore/banana.md, tests/fixtures/legacy-ignore/carrot-ignored/tomato.md, tests/fixtures/legacy-ignore/eggplant/clementine.md, tests/fixtures/legacy-ignore/litchee.md, tests/issue-173.tesh
* The `note.ignore` configuration property was renamed to `note.exclude`, to be more consistent with the CLI flags.
---
* Fix #313
=> Rename `note.ignore` config property to `note.exclude`

CHANGELOG.md, internal/util/strings/strings.go
=> increase buffer size to 2MB and display an error when it is exhausted

internal/adapter/fs/fs.go, internal/adapter/lsp/server.go, internal/cli/cmd/new.go
Package io/ioutil was deprecated in Go 1.16.
This replaces the use of functions from io/ioutil with equivalent ones from the io and os packages. This allows to more easily upgrade the version of Go used to build zk.
Refs:
https://pkg.go.dev/io/ioutil
=> Address io/ioutil deprecation

.github/workflows/build.yml
This sets up Go using the Go version from the `go.mod` file.
It makes it easier to keep the Go version in sync between the `go.mod` file and the GH workflow files.
=> chore(ci): use 'go-version-file' option in build workflow

internal/adapter/handlebars/handlebars_test.go
Adds a stable test for the `elapsed` template function.
=> test: add TestFormatDateHelperElapsed

tests/fixtures/issue-382/.zk/config.toml, tests/fixtures/issue-382/.zk/templates/default.md, tests/fixtures/issue-382/333h.md, tests/issue-382.tesh
This adds a test case for zk-org/zk#382 which found that dates without time
stamps in yaml frontmatter were causing the respective note to be returned when
quering the day *before* the note creation.
The test case was tested against commit 55d5487, which was before this 
bug was resolved: the test failed (the note from 24th of Jan was returned when querying 
for notes created on the 23rd of jan)
Ran again against the current commit (post zk-org/zk#382 being resolved) and it
passes.
Also, in contributing.md, mickael wrote that it's good practice that we make a test fixture per issue with tesh tests. 
But there was already a tests/markdown-yaml-frontmatter.tesh file. 
Should I instead add this new test coverage to that test fixture?
=> tesh test case for yaml dates without time stamp

README.md
This PR fixes an issue with the hyperlink to the getting-started doc in the GitHub pages generated site. The `href` in the HTML `div` is not mapped correctly, so we move the link out of the div into a separate line. Doesn't look as pretty but should work as expected.
=> Fix hyperlink from `README.md` to `docs/getting-started.md`

internal/adapter/lsp/document.go
PR to fix zk-org/zk#250. Links such as `[title](file:///file.go)` were returning an
lsp error "not found". The LSP does not actually check for the existence of
files via this format. Instead it was a symptom of the markdown link regex
checking, whereby the link was being understood as an internal markdown
document. Zk / lsp then tried to find the note `file:///file.example`, which it
if course couldn't, and so it was throwing the "not found" error.
This sollution copies the logic already present for embedded images, which is to
pick a defining syntactic element of the link (in this case, the third
occurrence of a '/' rune), and to skip that link with `continue`, effectively
ignoring it.
=> accept tripple dash file URIs as valid links

internal/adapter/lsp/document.go, internal/adapter/lsp/server.go
This commit introduces trigger completion: until now zk LSP generated completion only on auto trigger. In particular this fixes https://github.com/zk-org/zk-nvim/issues/155
The completion bugs came from three sources: there was a wrong implementation of tag completion which forgot to ignore the '#' character, the completion function never made a call for trigger completion, and offset for `textEdit` on link completion was hardcoded to `-2` which is wrong if there is an additional text entered before a trigger is pressed. This commit fixes these three bugs.
=> fix(lsp): fix trigger completion of zk LSP

internal/adapter/lsp/document.go
resolves: #194.
resolves: https://github.com/zk-org/zk-nvim/issues/161
I tried to be as thorough as possible, let me know if I missed any other markdown ways to denote code blocks. I am also including here two files I have used to test this fix:
[empty-note.md](https://github.com/zk-org/zk/files/14841478/empty-note.md)
[test-note.md](https://github.com/zk-org/zk/files/14841479/test-note.md)
=> fix(lsp): ignore diagnostic check within code blocks

internal/core/note_index.go, internal/util/paths/testdata/.walk-hidden/.hidden-dir/.hidden-file-in-hidden-dir, internal/util/paths/walk.go, internal/util/paths/walk_test.go
resolves: #271
The `index` function of `zk` calls a directory walk. That walk function was set to ignore all directories and files that had a period as a prefix. This applied then to the notebook root directory itself. This also effected commands such as `zk list`.
This fix is an initial approach to solving that by checking if the directory begins with a prefix _and_ the directory in question _does not_ equal the notebook root directory.
This equality check is done by getting the notebook directory from the `NotebookPath.Filename()` method, and checking it against the value of `filename` in `internal/util/paths/walk.go`.
Note: It was not possible to import the `core` package to `walk.go` as it created an import cycle. This is why it is instead accessed in `internal/core/note_index.go` …
=> allow notebook as hidden dir

go.mod, go.sum
resolves: #411
Our current version (v1.14.16) of `go-sqlite` breaks cross compilation to `musl` based distros such as Alpine.
We don't currently build for Alpine, but we can with this version bump.
I have an untested successful Alpine build in progress, just waiting on a report back whether it runs (see discussion in issue above).
Using the image in the [alpine branch of zk-xcompile](https://github.com/tjex/zk-xcompile/tree/alpine)
=> raise sqlite version for musl build compatibility

internal/util/fixtures/fixtures.go
Previously, the path was determined using `runtime.Caller`. However, in some cases, `runtime.Caller` will not return an absolute file path. This, for example, happens when `-trimprefix` is passed as a compilation option which is used by many downstream distributions (e.g. [Alpine Linux](https://gitlab.alpinelinux.org/alpine/abuild/-/blob/3.13.0/default.conf?ref_type=tags#L5)) via `GOFLAGS`. Thereby causing test failures on such distributions.
This commit attempts to work around that by exploiting the fact that `go test` sets the working directory to the currently tested package source. Hence, allowing us to determine the fixture path relative to this directory, and thereby fixing test failures with `-trimprefix`.
I ran into this file creating a zk package for Alpine Linux: …
=> Determine fixture path using the current working directory

internal/adapter/editor/editor.go
If I abort editing a file, `zk` shows 'failed to launch editor'. This message is not correct, since I explicitly aborted the operation after the editor successfully launched.
When using Vim, this is triggered by using `:cq`, which exits non-zero. With a GUI editor, this is usually achieved by pressing the Cancel/Abort button.
Update the error handling to show the correct error: if the editor executed and exited abnormally, indicate that the operation was aborted. Otherwise, show the previous message.
=> Fix mix-up in error message when aborting

internal/adapter/lsp/document.go
- Added check for magnet links (magnet:?xt) to prevent not found false alarms in LSP.
Context:
=> fix: magnet link

internal/core/config.go, internal/core/notebook_store.go, tests/cmd-init-defaults.tesh
resolves zk-org/zk#413
Braces needed to be escaped.
Updated tesh test to reflect this fix (it was previously built on an output with this bug from zk-org/zk#413 present).
Unfortunately all changes got lumped into one commit message. Lost track of how that happened. Will fix in squash
=> fix: default lsp config opts not being rendered

.github/workflows/gh-pages.yml
The gh pages fix from https://github.com/zk-org/zk/pull/387 setup deployment / build to occur on release publishing.
The documentation / readme is therefore stuck until the next zk semver release.
I think it's better to have the page rebuild on push / merge, as documentation updates are seemingly frequent.
@hugginsio what do you think?
=> gh-pages build on push, not release

internal/core/config.go, internal/core/notebook_store.go, internal/util/paths/paths.go, tests/cmd-init-defaults.tesh
This allows specifying paths relative to $HOME in the configuration file (this is particularly useful for the global config).
[note]
template = "~/.config/zk/default.md"
=> Expand tilde in config note.template

docs/editors-integration.md, docs/note-filtering.md, docs/notebook-housekeeping.md, internal/adapter/sqlite/note_dao.go, internal/cli/filtering.go, internal/core/note_find.go, tests/cmd-graph.tesh, tests/cmd-list.tesh, tests/fixtures/tagless/inline.md, tests/fixtures/tagless/tag-array.md, tests/fixtures/tagless/tagged.md, tests/fixtures/tagless/tagless.md, tests/tagless.tesh
Add support for `--tagless` to filter for notes that do not have tags per this discussion: https://github.com/zk-org/zk/discussions/449
=> Add feature: zk list --tagless

README.md
This link looks like it has been updated in https://github.com/zk-org/zk/pull/453.
=> Update link to neuron docs

internal/core/notebook_store.go, tests/cmd-init-defaults.tesh
New notebooks (`zk init`) use the legacy `ignore` config parameter which does not work anymore.
I believe this was one missed in #322
=> Rename 'ignore' to 'exclude' in default config

internal/adapter/handlebars/handlebars_test.go
go normalises the dates, so there shouldn't be an issue when arbitrarily adding +1 to a month (where at some point the test may be ran on Feb 30th, which would just become March 1st)
=> fix test. Set current day one month in advance

internal/cli/cmd/edit.go
The error message read "Found 0 note". This patch corrects it to "Found 0 notes.".
=> Fix error text when no notes found.

internal/core/config.go, internal/core/config_test.go, tests/fixtures/issue-490/.zk/config.toml, tests/fixtures/issue-490/.zk/templates/template1.md, tests/fixtures/issue-490/.zk/templates/template2.md, tests/issue-490.tesh
An attempt to fix the bug described in https://github.com/zk-org/zk/issues/490
The bug was due to early returning when a partial prefix match happened.
We now find the longest partial prefix match and return that instead.
=> fix: nested group rules

docs/conf.py, docs/index.rst
Having the version number in the title is not great for search engines. Old versions will be indexed and cause confusion.
I've opted for removing the version number completely as the docs site can also have changes that are ahead of the latest public version.
Until we implement proper version tracking on the site like [here](https://olgarithms.github.io/sphinx-tutorial/docs/9-versioning.html) I'm opting to leave the version out completely. 
It causes more confusion than good.
=> static site title and version clarification

.github/workflows/build-docs.yml, .github/workflows/gh-pages.yml, docs/conf.py
ubuntu-20 will soon be completely removed from support and will fail on runs.
=> ci: set gh-pages workflow to run on ubuntu-latest

internal/adapter/lsp/cmd_list.go
[zk list](https://github.com/zk-org/zk/blob/main/docs/tips/editors-integration.md#zklist)'s error messages says `zk.tag.list` in the error message, when it should be `zk list`
call the following lua code in neovim with the zk lsp attached:
```lua
require("zk.api").list("", {}, function(err, notes)
vim.print(err)
end)
```
the following error message is printed:
```
{
code = -32600,
message = "zk.tag.list expects a `select` option with the list of fields to return",
<metatable> = {
__tostring = <function 1>
}
}
```
=> Fix LSP error message

.github/ISSUE_TEMPLATE/feature_request.yml, internal/adapter/lsp/document.go
This PR fixes the crash described in #461.
The root cause of the problem was that the global state that tracks whether or not a line is in a code fence was not reset after each pass over the file. This behavior can be shown in the `test-wrap.md` file.
This would cause the `currentCodeBlockStart` to not always point to the fence.
Sometimes it would point to a line with len < 3, which resulted in a out of bounds read in `lines[currentCodeBlockStart][:3] == line[:3]`.
Another undefined state caused by this is where `lineIndex` < `currentCodeBlockStart`.
I manually tested by attaching the lsp to `nvim 0v0.10.4` on the following files:
[test-note.md](https://github.com/user-attachments/files/18490023/test-note.md)
[test-fence.md](https://github.com/user-attachments/files/18924318/test-fence.md) …
=> Fix LSP Crash in Code Fences

internal/adapter/fzf/note_filter.go
There was a --bind behavior change in fzf 0.53.0 which could be causing the error.
execute action is for executing an external program in the alternate screen without leaving fzf. In zk abort+execute was used to close fzf and open a zk instance.
become action is similar to execute, but it replaces the current fzf process with the specified command using execve(2) system call.
This should have similar behavior to the previous abort+execute action.
https://github.com/junegunn/fzf/issues/3865  
https://github.com/junegunn/fzf/blob/710ebdf9c14e0c88b0cfc843ce08edcdd4554571/man/man1/fzf.1#L1785-L1789  
https://github.com/junegunn/fzf/commit/6ea38b44384e7a09a3863465dc3cc7b93cd7e781
fixes: #518
=> fix: Ctrl+E does no longer create new notes in chooser

docs/config/config-group.md, internal/core/config.go, internal/core/config_test.go
As of right now, there's no way to match _across file separators_. For example, if I would like to match both `apple/ambrosia` and `melon/cantaloupe/ambrosia`, I would need to specify both paths:
```toml
[group."Ambrosia Fruit Varieties"]
paths = ["apple/ambrosia", "melon/cantaloupe/ambrosia"]
```
Note that `*/ambrosia` does __not__ work, since it doesn't match across `/`; it only matches `apple/ambrosia`
I would prefer to be able to specify just the `**/ambrosia` once, especially if I were a botanist trying to develop a highbush ambrosia blueberry that I would file it under `berry/blueberry/highbush/ambrosia`
We already use [doublestar](https://github.com/bmatcuk/doublestar) when looking for [excluded paths](https://github.com/zk-org/zk/blob/f4d3dc7113f5639fb262cb2d342419a8a1249814/intern …
=> Use doublestar for group paths

README.md
This PR is an alternative to #506.
The original explanation for this PR's change is at <https://github.com/zk-org/zk/pull/506#issuecomment-2753773638> and is copied below.
---
Nix is a complex beast, with a package management system that looks alien compared to other package managers. A comment on a Github issue is a poor place to explain all that is Nix, so I'll try to provide a short summary of Nix here, and just the parts that are immediately relevant to this issue.
One of the primary points of Nix is declarative package management and configuration. Whereas with other package managers the way to install something would be a shell command, e.g. `sudo apt install firefox` and `sudo pacman -S firefox`, the best way to install a package in Nix is editing configuration files. This is …
=> Stop using `nix-env -iA` and add better instructions for Nix users

internal/adapter/lsp/server.go
Fixes #435 and zk-org/zk-nvim#176.
After looking at the code and testing earlier versions, it seems that the issue was introduced in #397, which fixed the issue of triggering completion manually, but also introduced offsets that account for words instead of just using a `-2` offset. The `-2` offset worked for both `[[` and `((`, but the checks in #397 only accounted for `[[` which broke completion for `((`.
This PR just adds an extra condition to also catch `((`. Some notes:
- I don't really know go, so comments welcome
- It seems that trigger (non-auto) completion with  `[[|` was fixed by #397, but that `[[somewords|` still does not work. And it still does not work with these small updates (but `((|` works just like `[[`)
- I'm marking this as a draft for now because I want to double …
=> Fix completion of markdown links with LSP titles

.gitattributes, CONTRIBUTING.md, Makefile, VERSION.txt, main.go, tests/flag-version.tesh
Configure git to include the current version in tarballs generated via git-archive.
Fixes: https://github.com/zk-org/zk/issues/555
See: https://whynothugo.nl/journal/2024/12/16/injecting-project-versions-into-builds/
=> Include version in release tarballs

docs/config/config-notebook.md, docs/config/config.md, internal/cli/container.go
Always a nicety when programs provide an option like this. For my own usecase, I prefer to wrap config files into the nix store and point the program at it.  This variable adds this flexibility for zk.
=> feat: respect ZK_CONFIG_DIR as an override for global config location and update docs

tests/cmd-edit.tesh, tests/config-alias.tesh, tests/config-format-markdown-link.tesh, tests/config-format-markdown-tags.tesh, tests/config-note-default-title.tesh, tests/config-note-exclude.tesh, tests/config-note-filename.tesh, tests/config-note-id.tesh, tests/config-note-language.tesh, tests/config-note-template.tesh, tests/issue-173.tesh
Resolves #569 
Certain tesh cases are only failing in github ci. 
The common complaint is a backslash being seen as an illegal character. However there are some further issues, such as flags-version
The issue is that in some tests, config.toml files are being written from echo commands. In these echo commands, `\n` is being printed literarlly. `printf` needs to be used instead.
Commit 67c2dd5 proves this as `issue-173.tesh` no longer fails from that commit.
As to why tesh started failing only now / recently in CI with these standard cross shell incompatablity issues -- I have no idea.
=> Fix tesh cases failing with bash

tests/cmd-list-missing-backlink.tesh, tests/fixtures/missing-backlink/.zk/config.toml, tests/fixtures/missing-backlink/0wf6.md, tests/fixtures/missing-backlink/s0i1.md
`--missing-backlink` feature introduced in: #578
=> Add tesh case for missing backlink

internal/adapter/sqlite/note_dao.go, internal/adapter/sqlite/note_dao_test.go, internal/adapter/sqlite/note_integration_test.go
When following markdown links without extensions, zk incorrectly resolved to files with longer paths, which is often wrong when the shorter path is an exact match.
For example, the link "[text](2024-08-27)" resolved to "2024-08-27_ajct.md" instead of the intended "2024-08-27.md"
Title-based alphabetical sorting was overriding path-relevance ordering from href searches. Files with similar prefixes would be sorted by title rather than by path length/exactness.
Detect when path relevance should override title sorting for file-like searches, but attempt to preserve ordering for other scenarios.
=> Fix LSP navigating to the wrong link
