- CHANGELOG.md
- adapter/fzf/finder.go
- adapter/sqlite/fixtures/default/notes.yml
- adapter/sqlite/note_dao.go
- adapter/sqlite/note_dao_test.go
- adapter/sqlite/stmt.go
- cmd/finder_opts.go
- core/note/find.go
- docs/config-alias.md
- docs/note-filtering.md
- docs/note-frontmatter.md
* Find every mention of a note in your notebook with `--mention file.md`.
* This will look for occurrences of the note's title in other notes.
* To refer to a note using several names, you can use the [YAML frontmatter key `aliases`](https://publish.obsidian.md/help/How+to/Add+aliases+to+note). For example the note titled "Artificial Intelligence" might have: `aliases: [AI, robot]`
* To find only unlinked mentions, pair it with `--no-link-to`, e.g. `--mention file.md --no-link-to file.md`.
* Print metadata from the [YAML frontmatter](docs/note-frontmatter.md) in `list` output using `{{metadata.<key>}}`, e.g. `{{metadata.description}}`. Keys are normalized to lower case.
> Add the --mention filtering option

- CHANGELOG.md
- internal/adapter/lsp/server.go
* Fix completion with Neovim's built-in LSP client (contributed by [@cormacrelf](https://github.com/mickael-menu/zk/pull/39)).
> Fix completion with Neovim's built-in LSP client

- CHANGELOG.md
- internal/adapter/sqlite/note_dao.go
- internal/adapter/sqlite/note_dao_test.go
- internal/core/notebook.go
* Fix #16 Links with section anchors, e.g. `[[filename#section]]`.
> Fix links with section anchors

- internal/cli/cmd/new.go
> Fix crash when creating a new note fails

- README.md
There is an official package now: https://archlinux.org/packages/community/x86_64/zk/
> Add install instructions for Arch Linux.

- README.md
See https://github.com/mickael-menu/zk/pull/142
> Clarify the Homebrew instructions

- CHANGELOG.md
- internal/adapter/lsp/document.go
- internal/adapter/lsp/server.go
- internal/cli/cmd/init.go
- internal/cli/cmd/lsp.go
- internal/cli/container.go
- internal/cli/filtering.go
- internal/util/strings/strings.go
- internal/util/strings/strings_test.go
* [#144](https://github.com/mickael-menu/zk/issues/144) LSP auto-completion of YAML frontmatter tags.
---
* Fix #144
> LSP auto-completion of YAML frontmatter tags

- .github/workflows/build.yml
- Makefile
- tests/cmd-index.tesh
- tests/cmd-list-sort.tesh
- tests/cmd-tag-list-format.tesh
- tests/config-alias.tesh
- tests/config-filter.tesh
- tests/issue-23.tesh
- tests/markdown-yaml-frontmatter.tesh
Run the [`tesh`](https://github.com/mickael-menu/tesh) test suite during GitHub action checks.
> Run `tesh` with the GitHub checks

- .github/workflows/release.yml
> Bump the Homebrew formula on GitHub releases

- CHANGELOG.md
- internal/util/date/date.go
- tests/cmd-new.tesh
- tests/fixtures/new/.zk/config.toml
* [#152](https://github.com/mickael-menu/zk/issues/152) Incorrect timezone for natural dates.
---
* Fix #152
> Fix incorrect timezone for natural dates

- internal/adapter/lsp/util.go
Fixes #184. The changes should only affect Windows builds and will try to resolve file paths when the uri scheme is formatted as either `file:///...` or `file://...`.
> Fix file url parsing on Windows

- CHANGELOG.md
- internal/core/note_parse.go
- tests/fixtures/blank-slug/.zk/config.toml
- tests/issue-170.tesh
* [#170](https://github.com/mickael-menu/zk/issues/170) Broken wiki links in subdirectories.
---
* Fix #170
> Fix broken wiki links in subdirectories

- .github/workflows/release.yml
See https://github.com/mickael-menu/zk/issues/163#issuecomment-1115050286
> Fix running the Homebrew workflow

- CHANGELOG.md
- internal/adapter/sqlite/link_dao.go
- internal/adapter/sqlite/note_dao.go
- internal/adapter/sqlite/note_index.go
- internal/adapter/sqlite/note_index_test.go
- internal/adapter/sqlite/util.go
- internal/cli/container.go
- internal/core/link.go
- internal/core/note_index.go
- internal/core/note_new_test.go
- tests/cmd-init-defaults.tesh
- tests/cmd-init.tesh
- tests/fixtures/issue-23/template.md
- tests/issue-16.tesh
- tests/issue-20.tesh
- tests/issue-23.tesh
* Indexed links are now automatically updated when adding a new note, if it is a better match than the previous link target.
> Update existing links when adding a new note

- README.md
- docs/neuron.md
cf. https://github.com/EmaApps/emanote/pull/321
> neuron.md: Add link to docs for Emanote

- README.md
Also take the opportunity to unify the dashes.
> Add zk-spaced to list of related projects

- internal/adapter/handlebars/handlebars_test.go
> Fix `{{date}}` helper test

- README.md
Addressed in #376 , but didn't put the callout on it's own line, which resulted in it not rendering...
> Maintenance mode callout fix

- README.md
- docs/editors-integration.md
> Fix broken links

- docs/daily-journal.md
> Doc: how to edit today's daily note

- CHANGELOG.md
Update changelog for v0.14.1 release
> release zk v0.14.1

- docs/getting-started.md
While reading the getting started guide, it was not immediately clear to me how (a) tags can be added to files and how (b) one can reference other notes. This PR references the documents which explain these two aspects in greater detail in the appropriate sentences of the getting started guide.
> Doc: Improve getting started guide

- .github/workflows/build-binaries.yml
Forgot about doing this in #469
> fix: set ghcr.io urls to zk-org

- .github/workflows/build-binaries.yml
Need to authenticate to ghcr to pull builds in actions
> Build action

- .github/workflows/build-binaries.yml
Need to log in to ghcr in every singular job in build binaries action.
> login to ghcr at every step

- .github/workflows/build-binaries.yml
Linux arm runners are [https://github.com/orgs/community/discussions/148648](available), lets use them ;)
> use arm based linux runners for arm builds

- .github/workflows/release.yml
Resolves #504 (hopefully, first try)
> ci: fix token permissions and version tag sourcing

- .github/workflows/release.yml
Modifying the release.yml file on main so as to debug for #508 .
> Debug release.yml workflow

- CONTRIBUTING.md
- docs/conf.py
- docs/requirements.txt
- docs version bump to v0.14.2
- update contributing.md with better steps for documentation
- update requirements.txt with missing Sphinx package
> Bump docs version

- docs/tips/editors-integration.md
Old version numbers and fix table.
> Docs: small fixups

- internal/adapter/editor/editor.go
- internal/adapter/editor/suffix-windows.go
- internal/adapter/editor/suffix.go
Fixes #499 by removing /dev/tty on Windows
> Windows support to edit new files
